### ISSUE TITLE
Consider renaming basic data structures

### ISSUE THREAD

**Issue by skywall** [futuredapp/donut#42]
- `DonutDataset` - currently represents one item in graph - not ideal to call this `...set`
- `DonutData` - currently contains list of `DonutDatasets` and graph parameters - not ideal call this `data` because it's both raw data and configuration / parameters
- `DonutConfig` - seems ok

**Comment by SumeraMartin** [comment]
Do we want to rename these data structures in the both versions of the library? (I think that only apply for `DonutDataset`)

1. `DonutDataset` -> `DonutSection`

2. `DonutData` -> `DonutModel`
