### ISSUE TITLE
Use the library with minSdkVersion 19

### ISSUE THREAD

**Issue by eldon97** [futuredapp/donut#53]
I want to use this library, but my app has minSdkVersion 19. I force it using below code. What's the thing will be broken? or are there an alternative way to use this library in app that has minSdkVersion 19?
` <uses-sdk
        android:minSdkVersion="19"
        tools:overrideLibrary="app.futured.donut" />`

**Comment by matejsemancik** [comment]
Hi! We cannot guarantee a proper functionality on devices below API 21, but as far as everything compiles and works fine on these devices, you should be good to go :)

**Comment by eldon97** [comment]
argh, it turns out the compile is failed with error `android.view.InflateException: Binary XML file line #62: Error inflating class app.futured.donut.DonutProgressView` is there a way to solve this?

**Comment by eldon97** [comment]
I already solved it the compile failure and I create  PR #55  for that. But I still don't know if it breaks something or not. I'm so grateful if there are contributor who willing to check it.

**Comment by matejsemancik** [comment]
Yes, I checked it yesterday and problem was the API21+ constructor. Thanks for the PR, will look at that. We also consider changing the library to minSdk 19, so the manifest override would not be needed.
