### ISSUE TITLE
Is there a way to change the tip of the progress to flat instead round?

### ISSUE THREAD

**Issue by eldon97** [futuredapp/donut#54]
What I mean is this part, look at the below picture. Is there a way to change it to flat?
![image](https://user-images.githubusercontent.com/19554521/95184547-b7f91800-07f1-11eb-9a49-2421387160aa.png)

**Comment by SumeraMartin** [comment]
@eldon97 So far there is no way to change that but it shouldn't be hard to implement this change. I will take a look at it in the following days.

**Comment by matejsemancik** [comment]
Linking #30 as related issue

**Comment by eldon97** [comment]
it seems another person request this feature too.  @SumeraMartin thank you, I will wait for it 👍
