### ISSUE TITLE
Support with java.

### ISSUE THREAD

**Issue by DevKish0n** [futuredapp/donut#62]
Can I implement this in my JAVA based app?

**Comment by matejsemancik** [comment]
Should work, as Kotlin is interoperable with Java. Take a look at [docs](https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html). You will need to set up your Android project with Kotlin, though.

**Comment by DevKish0n** [comment]
It worked with java too.

**Comment by matejsemancik** [comment]
Glad you worked it out. Closing the issue.

**Comment by kish0n-eng** [comment]
> @kish0n-eng Any samples of code how you get it done? I'm trying to implement donut with my java app but without success.

@sysoppl I don't have any sample code. But I ve implemented on my project. I can help you. 

![received_3768852099836325.jpeg](https://user-images.githubusercontent.com/26185979/157916461-a07c452b-4810-4144-9ffb-621b6ee23592.jpeg)

**Comment by sysoppl** [comment]
I defined donut view
```
DonutProgressView aqiCircle;

...

aqiCircle = findViewById(R.id.aqi_donut);
```

My XML file contains donut view
```
        <app.futured.donut.DonutProgressView
            android:id="@+id/aqi_donut"
            android:layout_width="150dp"
            android:layout_height="150dp"
            android:layout_marginTop="25dp"
            app:donut_bgLineColor="@color/red_btn_bg_color"
            app:donut_gapAngle="270"
            app:donut_gapWidth="20"
            app:donut_strokeWidth="16dp"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />
```

and I'm adding values to it
```
aqiCircle.setCap(5f);
aqiCircle.addAmount("1", 1f, null);
```
I tried addAmout, setAmout, list etc but every time my view is the same (default)
![image](https://user-images.githubusercontent.com/30871217/157932362-e05d0000-cf08-4fe2-8097-2b2db28810fa.png)

**Comment by kish0n-eng** [comment]
@sysoppl 

[https://gist.github.com/kish0n-eng/6faa288385d8ec17683e95cd7345283f](please check out this gist.)

**Comment by kish0n-eng** [comment]
@sysoppl Please check out this [https://gist.github.com/kish0n-eng/6faa288385d8ec17683e95cd7345283f](gist)

**Comment by sysoppl** [comment]
Oh God, I tried List but I had to do something wrong, it was so simple 😅 Thank you so much!

**Comment by kish0n-eng** [comment]
@sysoppl My pleasure. 😊
