### ISSUE TITLE
Ques: GapWidth between sections

### ISSUE THREAD

**Issue by kdani41** [futuredapp/donut#66]
Thanks for this amazing library. 
Is it possible to control gap width between each section?

Currently the gap is for the overall chart I believe. Is there any way I can add that gap in between sections?

Something like this
![image](https://user-images.githubusercontent.com/7985118/108577384-dd914480-72ee-11eb-810c-01e400b5fbe4.png)

**Comment by SumeraMartin** [comment]
@kdani41 This feature is not directly supported but I believe that it can be done by adding sections with transparent color between sections where do you want to add gaps.

**Comment by matejsemancik** [comment]
I'm afraid this approach won't work, because each section is drawn from start of the circle and sections are stacked on each other, so transparent section will just show previous coloured section below it.

**Comment by kdani41** [comment]
@matejsemancik You're right I tried playing with the sample and this is what i get with these values :(
Having said that is there any another workaround i can do to display some gaps?

```kotlin
    private fun fillInitialData() {
        val sections = listOf(
            DonutSection(
                BlackCategory.name,
                getColorCompat(BlackCategory.colorRes),
                2f
            ),
            DonutSection(
                GreenCategory.name,
                Color.TRANSPARENT,
                1.2f
            ),
            DonutSection(
                OrangeCategory.name,
                getColorCompat(OrangeCategory.colorRes),
                1f
            )
        )

        donutProgressView.submitData(sections)

        updateIndicators()
    }
```
![sample](https://user-images.githubusercontent.com/7985118/108602095-276d3f80-736e-11eb-82a5-df3b4eaafde7.png)

**Comment by matejsemancik** [comment]
There is no workaround that you can use right now, sorry. The library was not built with such functionality in mind.
