### ISSUE TITLE
Question: Any way to find midpoint of a section?

### ISSUE THREAD

**Issue by Hrafnthor** [futuredapp/donut#67]
First off all, thank you for this fantastic library and all the time and effort that you have put into it!

I've been looking into the possibility of adding optional drawables to each section, and specifically I've been trying for a while now to figure out a good way to find the midpoint coordinates of each painted section for the placement of the drawables but have been unable to find a reliable way to do so. 

You wouldn't happen to have any pointers on how best to go about doing so?

**Comment by matejsemancik** [comment]
Hi! What kind of drawables are you looking to add to each section? Icons?
As of now, the `DonutProgressView` does not provide any info on where the sections are drawn, so for now, my only advice would be to fork and try to implement the drawables by yourself, since the functionality you require is out of scope.

**Comment by matejsemancik** [comment]
Sorry, maybe I understood the question differently. Well, in that case I would go about looking at `resolveState` and `getDrawAmountForLine` which are private methods of `DonutProgressView`. Each line is drawn from start of the circle and lines are basically rendered on top of each other. You could use `getDrawAmountForLine` method to calculate where each section starts and ends to determine the line midpoints. The `getDrawAmountForLine` returns normalised value between `0f..1f` which is then mapped to full circle length (from gap start to gap end).

**Comment by Hrafnthor** [comment]
No worries! Thank you for the info, this will surely help me.
