### ISSUE TITLE
How do we add text in the middle of the donut ?

### ISSUE THREAD

**Issue by jayanthsaikiran** [futuredapp/donut#68]
Can we implement this ?

![image](https://user-images.githubusercontent.com/46348137/111032393-03af8d80-8432-11eb-8bd2-1793fbf4583e.png)

**Comment by SumeraMartin** [comment]
Yes, you can do it even without the help of the library. Just add the donut and the text into the same layout (frame layout, constraint layout, etc.) and then center the text inside this layout.
```
<FrameLayout>
    <Donut />
    <TextView />
</FrameLayout>
```

**Comment by jayanthsaikiran** [comment]
> Yes, you can do it even without the help of the library. Just add the donut and the text into the same layout (frame layout, constraint layout, etc.) and then center the text inside this layout.
> 
> ```
> <FrameLayout>
>     <Donut />
>     <TextView />
> </FrameLayout>
> ```

Thanks, mate. Job Done. Sorry for the dumb question. I am new to android 😁.
