### ISSUE TITLE
Could not find app.futured.donut:library:2.1.0.

### ISSUE THREAD

**Issue by SakurajimaMaii** [futuredapp/donut#73]
implementation 'app.futured.donut:library:2.1.0'
I don’t know why this bug appears in the project

**Comment by matejsemancik** [comment]
Hi, I see that we have the old artifacts in README, forgot to update them during migration to mavenCentral 🤦 
The correct one is `app.futured.donut:donut:2.1.0`.
https://search.maven.org/search?q=g:app.futured.donut

I'm gonna fix that asap, sorry for inconvenience.

**Comment by SakurajimaMaii** [comment]
Thank you very much for your reply, my problem is solved
