### ISSUE TITLE
Colors in compose version not being rendered correctly

### ISSUE THREAD

**Issue by Stjin** [futuredapp/donut#83]
Hi,

I am facing an issue and after hours of playground testing I can't tell if I am missing something or if the behaviour between the compose and non-compose version is indeed different. I can't tell if this is a bug or not.

Please refer to the following gist:
https://gist.github.com/Stjin/807c430a25adebef76fae8a039cbc2b5

I have created an application with 2 activities
- 1 compose activity
- 1 native/xml activity

I implemented both the compose as well as the non-compose version of the donut library and recreated 2 identical setups.
However the end results is differently rendered.
It looks like the compose version reverses the colors?

<div>
<img src="https://user-images.githubusercontent.com/23135973/162574780-04ffb2b0-6d3b-4a4a-baec-d7179315bf89.png" alt="Compose" width="200"/>
Compose
<img src="https://user-images.githubusercontent.com/23135973/162574781-7a0048c4-513d-47d5-9979-213c4a150c26.png" alt="Native" width="200"/>
XML
</div>

<br><br>
Hope you can help me out ☺

**Comment by SumeraMartin** [comment]
Hi, you are right the colors are reversed in the compose version 🙈 I'm not sure if this is something that we want to change because it would break the functionality for the users who are already using the library. In case you are facing a problem with this then you can use `.reverse()` method on the sections in DonutModel.

**Comment by Stjin** [comment]
Reversing the list does change the location of the sections but does not change the colors. This does not seem to be the solution ad the donut colors are still rendered incorrectly but reversed.
From my perspective it would be better to have the compose version behave the same as the native version.

**Comment by SumeraMartin** [comment]
@Stjin Yeah, you are right. I see the issue. Colors are separated from data internally and then values are reversed but the colors are not. Silly mistake. Thanks for pointing it out. I'm creating a PR with a fix.

**Comment by SumeraMartin** [comment]
@Stjin version 2.2.2 with the fix is released

**Comment by Stjin** [comment]
Awesome! Thanks for the effort!

**Comment by Stjin** [comment]
The only difference I see now is the way the sections are rendered (the order or corner radius), not a huge deal but still a little bit of inconsistency.

<div>
<img src="https://user-images.githubusercontent.com/23135973/163787188-614f1c9d-2c7d-4610-91ab-110e668171c9.png" alt="Compose" width="200"/>
Compose
<img src="https://user-images.githubusercontent.com/23135973/163787190-0b62c75a-f403-4414-aef3-622d3b45e400.png" alt="Native" width="200"/>
XML
</div>

**Comment by Stjin** [comment]
@SumeraMartin Could you look into the inconsistency issue as well?
Thanks!
