### ISSUE TITLE
Dataset Click listener not available.

### ISSUE THREAD

**Issue by Afaqrehman98** [futuredapp/donut#87]
I am currently using v2.2.2 of this library and there is no click listener to detect which dataset was clicked. do I have to use a new version or what?

**Comment by SumeraMartin** [comment]
Hi, click listeners for datasets are not supported. But it sounds like something that could be added in the future.

**Comment by Afaqrehman98** [comment]
Hi,
Can I contribute for adding click listener?

**Comment by matejsemancik** [comment]
Closing as click listeners are currently out of scope of this library.
