### ISSUE TITLE
Half Donut Problem 

### ISSUE THREAD

**Issue by oguzhankrky** [futuredapp/donut#95]
I have a half donut but Constrait take up space like full donut. Could you help me about it ?
![Screen Shot 2023-10-06 at 10 59 29](https://github.com/futuredapp/donut/assets/42296306/ecdb23c6-698a-497c-9826-debbf9c3ace6)

**Comment by matejsemancik** [comment]
Hello 👋

The Donut view will always take up space needed to render full circle, no matter the utilised space of internal Canvas. This is intended behaviour.

**Comment by oguzhankrky** [comment]
how can I change it could you help me

**Comment by matejsemancik** [comment]
Unfortunately, the only thing you can do right now is to find a way to clip the view into half using your preferred method of choice (eg. Clipping Composable using `.clip` modififer, or using [`.drawWithContent`](https://stackoverflow.com/questions/71904066/jetpack-compose-cut-composable-in-half) method, but this would still leave you with rest of layout taking up unwanted space.

I'm adding this as a feature request -- the behavior you describe would need to be supported by the View implementation.

btw, do you use Android View, or Composable version?

**Comment by oguzhankrky** [comment]
I am using AndroidView . I guess I will be able to fix thanks to  using translationY this problem . Thank you

**Comment by oguzhankrky** [comment]
I found a solution for this problem . But it is not generic solution. Still, I'm sharing it for those who need it or to give you ideas for future developments. When OnMeasure height =  width / 2 and onSizeChanged function using this.centerY = h / 1f instead of this.centerY = h / 2f almost fix it .  The same regulations can be apply to compose version .
