### ISSUE TITLE
Add documentation on how to use snapshot versions

### ISSUE THREAD

**Issue by matejsemancik** [futuredapp/donut#98]
- Group snapshot versions based on major version: `2.X.X-SNAPSHOT`
- Document the snapshot version implementation in README

**Comment by mtotschnig** [comment]
@matejsemancik Are you there currently is a snapshot published?
![grafik](https://github.com/user-attachments/assets/08daa9bf-2d7c-400f-b736-fd9d476e258e)

**Comment by matejsemancik** [comment]
The snapshots are fixed now. I'm keeping this issue open for sorting out the documentation part.
